apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-web.name" . }}
  labels:
    {{- include "demo-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "demo-web.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
